seed: 39
model_save_dir: "./best_models"
wandb-project: null
out_directory: "./artifacts/results"

dataset:
  name: biosnap
  drug_featurizer_params:
    name: ["ecfp"] # ['maccs', 'ecfp', 'topological', 'atompair', 'rdkit', 'pattern', 'layered', 'erg', 'estate', 'avalon-count', 'rdkit-count', 'ecfp-count', 'fcfp-count', 'topological-count', 'atompair-count'}
    radius: 2
  target_featurizer_params:
    name: ['prottrans_bert_bfd', 'esm', 'bepler'] # ['one_hot_encoding', 'fasttext', 'glove', 'word2vec', 'prottrans_albert_bfd', 'prottrans_bert_bfd', 'prottrans_xlnet_uniref100', 'prottrans_t5_bfd', 'prottrans_t5_uniref50', 'prottrans_t5_xl_u50', 'esm', 'esm1b', 'esm1v', 'unirep', 'bepler']

model:
  name: "Modular"
  pred_layer_type: "DoubleHeadedSimilarity"
  nb_modules: 3
  hidden_sizes: [256, 256]
  latent_dim: 1024
  batch_size: 32
  n_epochs: 50
  lr: 1e-4
  lr_scheduler: "on_plateau"

fit_params:
  nb_ckpts: 1
  verbose: 1
